radsub/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'posts.views.home', name='home'),
    # url(r'^radsub/', include('radsub.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

posts/models.py
from django.db import models

# Create your models here.
class Keyword(models.Model):
	keyword = models.CharField("Keyword", max_length=20)
	description = models.TextField("Post Content", blank=True)
	createDate = models.DateTimeField('Created', auto_now_add=True)
	updateDate = models.DateTimeField('Updated', auto_now=True)

	def __unicode__(self):
	    return self.keyword 
	    
class Post(models.Model):
	title = models.CharField("Post Title", blank=True, max_length=100)
	slug = models.SlugField("Post Slug", blank=True, max_length=100)
	keywords = models.ManyToManyField(Keyword)
	excerpt = models.TextField("Post Excerpt", blank=True)
	thumbnail = models.ImageField("Thumbnail", upload_to="uploads/")
	content = models.TextField("Post Content", blank=True)
	addon = models.TextField("Post Addon HTML", blank=True)
	template = models.CharField(choices=(("top", "Content Top"), ("left", "Content Left"), ("bottom", "Content Bottom"), ("right", "Content Right")), max_length=50)
	contentWidth = models.IntegerField("Content Width")
	createDate = models.DateTimeField('Created', auto_now_add=True, editable=True)
	updateDate = models.DateTimeField('Updated', auto_now=True)
	publishDate = models.DateTimeField('Published')

	def __unicode__(self):
	    return self.title 

class Mod(models.Model):
	post = models.ForeignKey(Post)
	attribute = models.CharField("Attribute", choices=(("rotate", "Rotate"), ("rotate-x", "Rotate X"), ("rotate-y", "Rotate Y"), ("scale", "Scale"), ("x", "X"), ("y", "Y")), max_length=50)
	value = models.CharField("Value", max_length=20)
	
	def __unicode__(self):
		return self.attribute

posts/views.py
# Create your views here.
import posts
from django.http import HttpResponse, HttpRequest

from django.shortcuts import render_to_response
from django.template import RequestContext
def home(request):
	
	response = posts.models.Post.objects.all().order_by("-publishDate")[:6];
	
	try:
		debug = request.GET['debug']
		debug = "debug"
	except:
		debug = ""

	c = {
		"posts": response,
		"debug": debug
	}
			
	return render_to_response('show.html', c, context_instance=RequestContext(request))


def post(slug, request):
	c = {
		"posts": posts.models.Post.filter(slug=slug)
	}
	return render_to_response('post.html', c)

posts/templates/show.html
{% load staticfiles %}
{% load post_extras %}
<!doctype html>
<html>
	<head>
		<title>Lindsay.gs :: An energetic blog</title>
		<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
		<link href="//netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
		<link type="text/css" rel="stylesheet" href="{% static "css/app.min.css" %}" />
	</head>
	<body>
		<div id="home-tab">
			<a class="prev-slide" href="#">
				<i class="icon-chevron-left"></i>
			</a> 
			<a class="home" href="#home">
				<i class="icon-home"></i>
			</a>
			<a class="popup-menu" href="#">
				<i class="icon-list"></i>
			</a> 
			<a class="like-button" href="#">
				<i class="icon-facebook" style="color:#006699"></i>
			</a>
			<a class="tweet-button" href="#">
				<i class="icon-twitter" style="color:#66CCFF"></i>
			</a>
			<a class="next-slide" href="#">
				<i class="icon-chevron-right"></i>
			</a>
		</div>
		<div id="impress">
			{% if debug %}
			<div id="#debug" class="slide step debug" data-x="0" data-y="0" data-scale="7" data-rotate="180">
			</div> 
			{% endif %}
			<div id="home" class="step slide {{ debug }}" data-x="0" data-y="0" data-scale="2" data-rotate="180">
				<div class="row-fluid">
					<div class="span12">
						<div class="row-fluid">
							<div class="span12">
								<h1><span class="grey">Lindsay.gs</span></h1>
							</div>
						</div>
						<div class="row-fluid">
							<div class="span6">
								<ul class="post-menu">
							    {% if posts %}
						            {% for post in posts %}
										<li>
											<div class="row-fluid">
												<div class="span12">
													<div class="title"><span class="gray-date">{{ post.publishDate|date:"M. jS" }}</span> <a href="#{{ post.slug }}">{{ post.title }}</a></div>
													<p class="excerpt">{{ post.excerpt }}</p>
												</div>
											</div>
										</li>
								 	    {% if forloop.counter|divisibleby:3 %}
						            		</ul></div>
						            		<div class="span6"><ul class="post-menu">
						            	{% endif %}
						            {% endfor %}
					            {% endif %}	
								</ul>
							</div>
						</div>
					</div>
				</div>
		    </div>	
			{% if posts %}
				{% for post in posts %}
					<div id="{{ post.slug }}" class="step slide {{ debug }} {{ post.slug }}" {% if post.mod_set.all %}{% for attr in post.mod_set.all %} data-{{ attr.attribute }}="{{ attr.value }}"{% endfor %}{% endif %}>
					
					

						{% if debug %}<h1 class='debug-slug'>{{ post.slug }}</h1>{% endif %}
						{% if post.template = "top" %}
							<div>
								<h3 class="date">{{ post.publishDate|date:"M. jS" }}</h3>
									<h1>
										{% if user.is_authenticated %}
											<a class="edit" target="_blank" href="/admin/posts/post/{{ post.id }}">
												<i class="icon-cog" style="color:white"></i>
											</a>
										{% endif %}
										{{ post.title }}
									</h1>
								{{ post.content|safe }}
							</div>
							<div>{{ post.addon|safe }}</div>
						{% elif post.template = "left" %}
							<div class="row-fluid">
								<div class="span{{ post.contentWidth }}">
									<h3 class="date">{{ post.publishDate|date:"M. jS" }}</h3>
									<h1>
										{% if user.is_authenticated %}
											<a class="edit" target="_blank" href="/admin/posts/post/{{ post.id }}">
												<i class="icon-cog" style="color:white"></i>
											</a>
										{% endif %}
										{{ post.title }}
									</h1>
									{{ post.content|safe }}
								</div>
								<div class="span{{ post.contentWidth|diff:12 }}">{{ post.addon|safe }}</div>
							</div>
						{% elif post.template = "bottom" %}
							<div>
								{{ post.addon|safe }}
							</div>
							<div>
								<h3 class="date">{{ post.publishDate|date:"M. jS" }}</h3>
									<h1>
										{% if user.is_authenticated %}
											<a class="edit" target="_blank" href="/admin/posts/post/{{ post.id }}">
												<i class="icon-cog" style="color:white"></i>
											</a>
										{% endif %}
										{{ post.title }}
									</h1>
								{{ post.content|safe }}</div>
						{% elif post.template = "right" %}
							<div class="row-fluid">
								<div class="span{{ post.contentWidth|diff:12 }}">{{ post.addon|safe }}</div>
								<div class="span{{ post.contentWidth }}">
									<h3 class="date">{{ post.publishDate|date:"M. jS" }}</h3>
									<h1>
										{% if user.is_authenticated %}
											<a class="edit" target="_blank" href="/admin/posts/post/{{ post.id }}">
												<i class="icon-cog" style="color:white"></i>
											</a>
										{% endif %}
										{{ post.title }}
									</h1>
									{{ post.content|safe }}
								</div>
							</div>
						{% endif %}
					</div>
				{% endfor %}
			{% endif %}
		</div>		
		
		<div class="popup-content hider">
		    {% if posts %}
		    	<ul>
		    		<li>
		    			<h3>POSTS</h3>
		    		</li>
	            {% for post in posts %}
	            	<li>
	            		<a class="title {{ post.slug }}" href="#{{ post.slug }}"><span class="gray-date">{{ post.publishDate|date:"n/j" }}</span> {{ post.title }}</a>
	            		<!-- <p>{{ post.excerpt }}</p> -->
	            	</li>
	            {% endfor %}
		    	</ul>
	        {% endif %}
	        <div class="arrow-bottom"></div>
		</div>
		
		
		<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
		<script src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
		<script src="{% static "js/impress.js" %}"></script>
		<script type="text/javascript" src="{% static "js/app.min.js" %}"></script>
	</body>
</html>